# Generated by Django 2.1.5 on 2019-01-16 16:59

import datetime
from django.db import migrations, models
from django.db import models, migrations
from django.utils import timezone






class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(default=timezone.now)),

            ],
        ),
    ]
